name: "Continuous Integration"

on:
  pull_request:
    branches: [ "main" ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    name: Static Analysis

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install deps
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Execute type checking
        run: vendor/bin/phpstan analyse

  tests:
    runs-on: ubuntu-latest
    name: Tests

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: ''
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USERNAME: root
      DB_PASSWORD: ""

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - uses: actions/checkout@v4

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Install Deps
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Install NPM Deps
        run: npm ci

      - name: Build Front-End Assets
        run: npm run build

      - name: Run Migrations
        run: php artisan migrate:fresh

      - name: Generate key
        run: php artisan key:generate

      - name: Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests
        run: vendor/bin/phpunit
